### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by emirod-2020** [sergeystoyan/PdfDocumentParser#1]
Hello, I download PdfDocumentParser (wpf version) code in my site. I tried compile with VS 2013 and Framework 4.7.1 bat I found many compile errors, especially with PdfDocumentParser library. I got compile CliverWinRoutines and CliWpfRoutines. I tried with older release versions and neither. What could be the problem?

PD. Sorry for my bad english

**Comment by sergeystoyan** [comment]
Hi, you have to use the last pre-release.
