### ISSUE TITLE
SampleParser application

### ISSUE THREAD

**Issue by GraniteStateCollege** [sergeystoyan/PdfDocumentParser#3]
In Program.cs the call to initialize needs a static cast to int for Log.Level to work.

Log.Initialize(Log.Mode.ALL_LOGS_ARE_IN_SAME_FOLDER, new System.Collections.Generic.List<string> { Log.CompanyCommonDataDir }, **Log.Level.ALL);**

Log.Initialize(Log.Mode.FOLDER_PER_SESSION, new System.Collections.Generic.List<string> { Log.CompanyCommonDataDir }, **(int)Log.Level.ALL**);

Also, **ALL_LOGS_ARE_IN_SAME_FOLDER** is not defined in the enum in Mode in Log.cs

**Comment by sergeystoyan** [comment]
Thank you. It has been fixed in the master branch.
To avoid such issues you can use the last release code.
